import click
import os
import json
import subprocess
import platform
from pathlib import Path
from cget.utils import get_default_branch
import urllib.request


@click.command("build")
@click.option("--generator", default=None, help="CMake generator to use.")
@click.option("--build-dir", default="./build", help="Build path")
@click.option("--verbose", is_flag=True, default=False, help="Verbose output")
def build_command(generator: str, build_dir, verbose):
  """Install all dependencies and build project"""
  
  project_root = Path(".")
  cget_path = project_root / "cget.json"
  cpm_path = project_root / "cmake" / "CPM.cmake"
  cmake_path = project_root / "CMakeLists.txt"
  dependencies_path = project_root / "_dependencies.cmake"
  build_dir = Path(build_dir)

  if not cget_path.exists():
    click.echo("Error: cget.json not found.")
    return
  
  if not cmake_path.exists():
    click.echo("Error: CMakeLists.txt not found.")
    return
  
  if not cpm_path.exists():
    click.echo("Downloading CPM.cmake...")
    os.makedirs(project_root / "cmake", exist_ok=True)
    url = "https://github.com/cpm-cmake/CPM.cmake/releases/latest/download/CPM.cmake"
    urllib.request.urlretrieve(url, cpm_path)
    click.echo("CPM.cmake downloaded")

  with open(cget_path, "r") as f:
    data = json.load(f)

  dependencies = data.get("dependencies", [])
  if not dependencies:
    click.echo("No dependencies listed in cget.json")
  else:
    click.echo(f"Generating {dependencies_path.name}...")

    lines = [
      "# Auto-generated by cget build",
      "include(cmake/CPM.cmake)",
      "",
      "set(DEPENDENCY_LIBS)",
      "set(MACROS)"
    ]

    current_platform = platform.system().lower()

    for dep in dependencies:
      if "platforms" in dep and current_platform not in dep["platforms"]:
        continue

      name: str = dep["name"]
      source = dep["source"]
      version = dep.get("version", "latest")

      lines.append("CPMAddPackage(")
      lines.append(f"  NAME {name}")
      lines.append(f"  GITHUB_REPOSITORY {source}")
      lines.append(f"  GIT_SHALLOW TRUE")
      if version != "latest":
        lines.append(f"  VERSION {version}")
      else:
        branch = get_default_branch(source)
        lines.append(f"  GIT_TAG {branch}")
      lines.append(")\n")

      lines.append(f"list(APPEND DEPENDENCY_LIBS {name}::{name})")
      lines.append(f"list(APPEND MACROS HAS_{name.capitalize()})")

    lines.append("# end of dependencies")

    with open(dependencies_path, "w") as f:
      f.write("\n".join(lines))

    click.echo("_dependencies.cmake generated.")
  
  build_dir.mkdir(exist_ok=True)

  click.echo("Running CMake configuration...")
  cmd = ["cmake", ".."]
  if verbose:
      cmd.append("--verbose")
  if generator:
    cmd.append("-G")
    cmd.append(f"{generator}")
  result = subprocess.run(cmd, cwd=build_dir)
  if result.returncode != 0:
    click.echo("CMake configuration failed.")
    return
  
  click.echo("Building project...")
  result = subprocess.run(["cmake", "--build", "."], cwd=build_dir)
  if result.returncode != 0:
    click.echo("Build failed.")
    return
  
  click.echo("Build complete.")